spring:
  application:
    name: springAiDemo
  mybatis:
    mapper-locations: classpath:mapper/*.xml  # 如果你使用 XML 方式写 SQL
    type-aliases-package: com.dg.springaidemo.chatmemory.pojo  # 可选，给 ChatMessage 起别名
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  profiles:
    active: local
  logging:
    level: debug
server:
  port: 8100
  servlet:
    context-path: /api


# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

